include ':app'
//include ':capacitor-android'
//project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')




include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')

include ':capacitor-haptics'
project(':capacitor-haptics').projectDir = new File('../node_modules/@capacitor/haptics/android')
